import type { DraftCard, Season } from "@/lib/types";
import cardsData from "@/data/rlcs-cards.json";
import seasonsData from "@/data/rlcs-seasons-meta.json";

// Generated by scripts/build-roster-data.py from Liquipedia's RLCS season pages (CC-BY-SA 3.0).
// Rosters, roles (incl. genuine SUBSTITUTE/COACH tags) and regions are sourced facts; ratings are
// a game-balance heuristic (team strength + individual signals, normalized against that season's
// full player pool) and portraits are hotlinked from Liquipedia where a licensed image exists.
export const seedCards: DraftCard[] = cardsData as DraftCard[];

export const seasons: Season[] = [...(seasonsData as Season[])].sort((a, b) => b.year - a.year);
